# Fontiles configuration file

# Metadata about this instance of Fontiles
name: Fontiles
description: An open source font server, delivering beautiful fonts to the general public.
hoster: '@encadyma'
host: http://localhost:5000

# font_paths (required) - Defines paths for where fonts are located (in Fontile form)
font_paths:
- "./fonts"

# fonts (required) - a list of font families that Fontiles should search for
fonts:
- Fascinate Inline
- Righteous
- Source Sans Pro
- Josefin Slab
- Manrope